version: "3.4"

services:
  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-6.4-latest
    container_name: ${NAME}
    hostname: ${NAME}
    env_file:
      - .env
    environment:
      - ZBX_HOSTNAME=${NAME}
      - ZBX_SERVER_HOST=zabbix-server
    ports:
      - "10050:10050"
    restart: always
    extra_hosts:
      - "zabbix-server:${SERVER_IP}" # change this to your zabbix server ip
    networks:
      - zabbix-net

networks:
  zabbix-net:
    name: zabbix-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.240.0/20
